FROM jupyter/scipy-notebook

USER root
COPY . .

RUN python setup.py install

# this should run just fine
RUN asekuro test tests/notebooks/data-nb.ipynb
RUN asekuro test tests/notebooks/good-nb.ipynb
RUN asekuro test tests/notebooks/good-nb-metadata.ipynb